"use client";
import { useEffect, useState, useTransition } from "react";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { applyCouponAction } from "@/app/(storefront)/checkout/coupon-actions";
import { placeOrderAction } from "@/app/(storefront)/checkout/order-actions";
import { getShippingQuoteAction } from "@/app/(storefront)/checkout/shipping-actions";
import { computeCustomerShippingFee, computeExpressFee, type ShippingMethodCode } from "@/lib/shipping/rules";
import type { ShippingAddressForm, ShippingQuoteData } from "./shipping-step";
export type PaymentMethod = "STRIPE" | "VNPAY" | "COD";
const fmt = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" });
export function PaymentStep({ subtotal, shippingAddress, initialQuote, guestEmail, onBack, onSummaryChange }: { subtotal: number; shippingAddress: ShippingAddressForm; initialQuote?: ShippingQuoteData; guestEmail?: string; onBack: () => void; onSummaryChange?: (summary: { discountAmount: number; couponId?: string; couponCode?: string; shippingFee?: number }) => void }) {
  const [couponInput, setCouponInput] = useState(""); const [coupon, setCoupon] = useState<{ id: string; code: string; discountAmount: number } | null>(null); const [couponError, setCouponError] = useState<string | null>(null); const [method, setMethod] = useState<PaymentMethod>("STRIPE"); const [shippingMethod, setShippingMethod] = useState<ShippingMethodCode>("STANDARD"); const [quote, setQuote] = useState<ShippingQuoteData | null>(initialQuote ?? null); const [quoteError, setQuoteError] = useState<string | null>(null); const [orderError, setOrderError] = useState<string | null>(null); const [isApplying, startApplying] = useTransition(); const [isPlacing, startPlacing] = useTransition(); const [isQuoting, startQuoting] = useTransition();
  useEffect(() => { if (initialQuote) return; startQuoting(async () => { setQuoteError(null); const result = await getShippingQuoteAction({ city: shippingAddress.city, ward: shippingAddress.ward }); if (!result.ok) { setQuoteError(result.error); setQuote(null); return; } setQuote(result); }); }, [shippingAddress.city, shippingAddress.ward, initialQuote]);
  const discountAmount = coupon?.discountAmount ?? 0; const standard = quote ? computeCustomerShippingFee({ method: "STANDARD", carrierFee: quote.carrierFee, discountedSubtotal: subtotal - discountAmount, freeShipThreshold: quote.freeShipThreshold }) : null; const EXPRESS_SHIPPING_FEE = quote ? computeExpressFee(quote.carrierFee) : 0; const shippingFee = shippingMethod === "EXPRESS" && quote ? EXPRESS_SHIPPING_FEE : standard?.customerFee;
  useEffect(() => { onSummaryChange?.({ discountAmount, couponId: coupon?.id, couponCode: coupon?.code, shippingFee }); }, [discountAmount, coupon?.id, coupon?.code, shippingFee, onSummaryChange]);
  function applyCoupon() { if (!couponInput.trim()) return; startApplying(async () => { const result = await applyCouponAction(couponInput, subtotal); if (!result.ok) { setCouponError(result.error); setCoupon(null); return; } setCoupon({ id: result.couponId, code: result.couponCode, discountAmount: result.discountAmount }); }); }
  function placeOrder() { startPlacing(async () => { const result = await placeOrderAction({ shippingAddress, guestEmail, method, shippingMethod, couponId: coupon?.id, couponCode: coupon?.code, discountAmount: coupon?.discountAmount }); if (!result.ok) { setOrderError(result.error); return; } window.location.href = result.redirectUrl; }); }
  const canPlace = !isPlacing && !isQuoting && !quoteError && quote !== null;
  return <div className="space-y-6"><h2 className="font-hand text-xl uppercase text-foreground">Thanh toán</h2><div><label className="mb-2 block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Mã giảm giá</label><div className="flex gap-2"><input value={couponInput} onChange={(event) => setCouponInput(event.target.value)} placeholder="Nhập mã" disabled={!!coupon} className="min-h-12 flex-1 border border-input bg-transparent px-3.5 text-[11px]" />{coupon ? <Button type="button" variant="outline" onClick={() => { setCoupon(null); setCouponInput(""); }}>Gỡ mã</Button> : <Button type="button" variant="outline" onClick={applyCoupon} disabled={isApplying}>Áp dụng</Button>}</div>{couponError && <p className="mt-1 text-xs text-destructive">{couponError}</p>}</div><div><label className="mb-2 block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Phương thức giao hàng</label>{isQuoting && <p className="text-xs text-muted-foreground">Đang tính phí vận chuyển...</p>}{quoteError && <p className="text-xs text-destructive">{quoteError}</p>}{quote && <div className="divide-y divide-border border border-border"><label className="flex cursor-pointer items-center justify-between p-4 text-xs"><span><input type="radio" name="shippingMethod" checked={shippingMethod === "STANDARD"} onChange={() => setShippingMethod("STANDARD")} /> Giao tiêu chuẩn</span><span>{standard?.customerFee === 0 ? "Miễn phí" : fmt.format(standard?.customerFee ?? 0)}</span></label><label className="flex cursor-pointer items-center justify-between p-4 text-xs"><span><input type="radio" name="shippingMethod" checked={shippingMethod === "EXPRESS"} onChange={() => setShippingMethod("EXPRESS")} /> Giao hỏa tốc</span><span>{fmt.format(EXPRESS_SHIPPING_FEE)}</span></label></div>}</div><div><label className="mb-2 block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Phương thức thanh toán</label><div className="divide-y divide-border border border-border">{([ ["STRIPE", "Thẻ quốc tế (Visa/Mastercard)"], ["VNPAY", "VNPay"], ["COD", "Thanh toán khi nhận hàng (COD)"] ] as const).map(([value, label]) => <label key={value} className="flex cursor-pointer items-center gap-3 p-4 text-xs"><input type="radio" name="method" checked={method === value} onChange={() => setMethod(value)} />{label}</label>)}</div></div>{orderError && <p className="text-sm text-destructive">{orderError}</p>}<div className="flex gap-3"><Button type="button" variant="outline" onClick={onBack}><ArrowLeft className="size-3.5" /> Quay lại</Button><Button className="flex-1" onClick={placeOrder} disabled={!canPlace}>{isPlacing ? "Đang xử lý..." : "Đặt hàng"}</Button></div></div>;
}
