"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { resetPasswordAction } from "./actions";

export function ResetPasswordForm({ token }: { token: string | null }) {
  const router = useRouter();
  const [form, setForm] = useState({ password: "", confirmPassword: "" });
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [isPending, startTransition] = useTransition();
  if (!token) return <div className="w-full max-w-[420px]"><div className="border border-border bg-foreground/[0.03] p-6"><p className="font-hand text-sm uppercase tracking-[0.15em] text-foreground">Link không hợp lệ</p><p className="mt-2 text-[12px] text-muted-foreground">Thiếu token đặt lại mật khẩu. Vui lòng yêu cầu link mới.</p><Link href="/forgot-password" className="mt-4 inline-block text-[11px] uppercase tracking-[0.15em] text-foreground hover:opacity-60">Yêu cầu link mới →</Link></div></div>;
  function handleSubmit(event: React.FormEvent) { event.preventDefault(); setError(null); if (form.password.length < 8) return setError("Mật khẩu phải có ít nhất 8 ký tự."); if (form.password !== form.confirmPassword) return setError("Mật khẩu xác nhận không khớp."); startTransition(async () => { const result = await resetPasswordAction(token!, form.password); if (!result.ok) return setError(result.error); setSuccess(true); setTimeout(() => router.push("/sign-in"), 1500); }); }
  return <div className="w-full max-w-[420px]"><div className="mb-10"><span className="text-[10px] uppercase tracking-[0.35em] text-muted-foreground">Reset / 04</span><h1 className="mt-4 font-hand text-3xl font-bold uppercase tracking-tight text-foreground">Đặt mật khẩu mới</h1><p className="mt-3 text-[12px] leading-relaxed text-muted-foreground">Nhập mật khẩu mới cho tài khoản của bạn.</p></div>{success ? <div className="border border-border bg-foreground/[0.03] p-6"><p className="font-hand text-sm uppercase tracking-[0.15em] text-foreground">Đổi mật khẩu thành công</p><p className="mt-2 text-[12px] text-muted-foreground">Đang chuyển tới trang đăng nhập...</p></div> : <form onSubmit={handleSubmit} className="space-y-5"><label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Mật khẩu mới (tối thiểu 8 ký tự)</span><input required type="password" placeholder="••••••••" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="w-full border border-border bg-transparent px-4 py-3 font-mono text-sm text-foreground placeholder:text-muted-foreground/60 outline-none transition-colors focus:border-foreground" /></label><label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Xác nhận mật khẩu mới</span><input required type="password" placeholder="••••••••" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} className="w-full border border-border bg-transparent px-4 py-3 font-mono text-sm text-foreground placeholder:text-muted-foreground/60 outline-none transition-colors focus:border-foreground" /></label>{error && <p className="text-sm text-destructive">{error}</p>}<button type="submit" disabled={isPending} className="group flex w-full items-center justify-between border border-foreground bg-foreground px-5 py-4 text-[11px] font-medium uppercase tracking-[0.2em] text-black transition-colors hover:bg-transparent hover:text-foreground disabled:opacity-50"><span>{isPending ? "Đang lưu..." : "Đặt mật khẩu mới"}</span><ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" strokeWidth={1.5} /></button></form>}</div>;
}
